name: ArXiv Paper Watch

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  watch:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to commit changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0  # Fetch full history for git operations

      - name: Set up Python 3.13
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Create .env file from secret
        run: echo "${{ secrets.DOTENV }}" > .env

      - name: Run arXiv watcher
        run: uv run python -m arxivwatch.main

      - name: Commit updated paper IDs
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add notified_papers.json
          git diff --staged --quiet || git commit -m "Update notified papers [skip ci]"
          git push
        if: always()  # Always try to commit, even if the watcher fails
