name: ArXiv Paper Watch

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  watch:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to commit changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch full history for git operations

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Create .env file from secret
        run: echo "${{ secrets.DOTENV }}" > .env

      - name: Run arXiv watcher
        run: uv run python -m arxivwatch.main

      - name: Commit updated paper IDs
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add notified_papers.json
          git diff --staged --quiet || git commit -m "Update notified papers [skip ci]"
          git push
        if: always()  # Always try to commit, even if the watcher fails